src/runtime/runtime.c
https://github.com/probonopd/static-tools/pull/42
Thanks @lalten
=> Preserve timestamps when extracting the squashfs

build.sh, chroot_build.sh, src/runtime/Makefile
We are not interested in updating the major version of the statically linked libfuse all the time. However, it has been said that upstream does not provide security fixes for libfuse2 anymore (is there a link to this?). Hence, we should use libfuse3 in the hope that the FUSE project will stay with that major version indefinitely.
[libfuse2 CVEs](https://www.cvedetails.com/vulnerability-list.php?vendor_id=3090&product_id=0&version_id=0&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&month=0&cweid=0&order=1&trc=5&sha=04362d83280f8efe4c0f9668df424235042af263)
=> Use libfuse3

.github/workflows/build.yaml, build.sh, chroot_build.sh
This PR removes the need for [uraimo/run-on-arch-action](https://github.com/uraimo/run-on-arch-action).
Advantages:
* We can now pin all ingredients including Alpine Linux for all architectures
* Less complex
* Fewer external dependencies
* No more Docker needed
* All architectures now build in the same way
* Build speed did not suffer (this one surprised me)
=> Remove uraimo/run-on-arch-action

.github/workflows/build.yaml, build.sh, chroot_build.sh
Implement improvements suggested by @TheAssassin
=> Satisfy shellcheck; do not install apt packages from shell script

build.sh
Optimize for size; thanks @s09bQ5
https://github.com/AppImage/AppImageKit/issues/877#issuecomment-1597855286
=> Optimize for size

build.sh, chroot_build.sh, patches/libfuse/mount.c.diff
Build static libfuse3 with a patch to find `fusermount` in the following way:
1. Absolute path contained in the `FUSERMOUNT_PROG` environment variable
2. `fusermount3` on the `$PATH`
3. `fusermount` on the `$PATH` (known to work for our purposes)
4. `fusermount4...99` on the `$PATH`(speculative attempt at future-proofing; but better than not trying at all)
Closes https://github.com/AppImage/type2-runtime/issues/10
=> Build patched libfuse3 to find more fusermount binaries

.github/workflows/build.yaml
[pyuploadtool](https://github.com/TheAssassin/pyuploadtool/) is the spiritual successor to uploadtool.sh. While adding a lot of error handling, it basically provides the same experience: create continuous releases on the main branch, create releases upon tags, otherwise skip the upload.
=> Upload to GitHub releases with pyuploadtool

src/runtime/data_sections.ld
This allows tools like AppImageLauncher to reliably detect that the AppImage's runtime is static and that it supports `TARGET_APPIMAGE`.
=> Add undocumented "static" marker for AppImageLauncher

src/runtime/runtime.c
This seems to fix
* #51
@TheAssassin I am going to merge this as an emergency fix (since the runtime segfaults without this, this won't make it worse), please do carefully review afterwards nonetheless. Thanks!
=> Fix #51 segfault

chroot/build.sh, chroot/chroot_build.sh, scripts/build-in-container.sh, src/runtime/Makefile
fuse2 is no longer supported. I also fixed a few oversights from its removal.
Fixes https://github.com/AppImage/appimagetool/issues/58.
=> Remove superfluous -type3 suffix from artifacts

scripts/build-in-container.sh
=> Fix arch detection x86 64

src/runtime/Makefile
Remove redundant steps in an effort to further simplify things.
I also think there was a typo in there.
Every line of code we can remove is a line of code that can't have a bug and won't need maintenance.
=> Simplify Makefile

scripts/build-in-container.sh
Along with the modifications to the strip call, this seems to fix the broken relationship between the two files. Also, one no longer needs to load the debug symbols manually.
Ideally, one can put the runtime.debug file in the same directory as the AppImage, then run gdb my.AppImage.
Changes inspired by https://invent.kde.org/packaging/craft/-/blob/7c627a015c72ea7da4177375729dfe21e1810755/bin/utils.py#L1305-1305.
Fixes #25.
=> Add GNU debug link to load debug symbols in gdb

.github/workflows/build.yaml
A potential security issue has been fixed in download-artifact. Its update also requires an update of the corresponding upload action. I thought it's a good idea to update the rest as well.
=> Update all actions

patches/libfuse/mount.c.diff, src/runtime/runtime.c
This approach avoids tricky patching of upstream code and exports `FUSERMOUNT_PROG` instead.
Closes #15, #16, #31, #32, #35, #36, #37
=> Find usermountN and set FUSERMOUNT_PROG if not set

src/runtime/Makefile
Should be standard nowadays. It allows the kernel to enable some security-related features like ASLR.
=> Make binaries position independent

scripts/common/install-dependencies.sh, src/runtime/runtime.c
We used a pinned commit that enabled Zstd support but we can just use the latest release as well. The minor code modification is needed because the function's signature has changed upstream.
=> Update squashfuse to latest release

scripts/chroot/build.sh, scripts/docker/Dockerfile, src/runtime/Makefile
gcc is not capable of linking with -static-pie, therefore we switch to using clang.
This PR allows us to use https://github.com/io12/userland-execve-rust and apparently also AppImageLauncher's binfmt-bypass (via `TARGET_APPIMAGE`) to run AppImages with this static runtime.
Fixes #87.
=> Build static PIE binaries with clang

src/runtime/runtime.c
Closes #92
@mehmetakbulut @lalten does this fix the issue?
=> auto_unmount

scripts/chroot/build.sh, scripts/docker/Dockerfile, src/runtime/Makefile
Reverts AppImage/type2-runtime#88
due to https://github.com/AppImage/type2-runtime/issues/96
A new PR can be made in case it can be done in a way that does not cause #96.
=> Revert "Build static PIE binaries with clang"

.github/workflows/build.yaml
So far, pyuploadtool was marking the continuous release as "prerelease", resulting it in being hidden here:
This has led to confusion, as people thought there is "no recent release". In fact, continuous is always the only supported release as I have no capacity to even look at bugs filed against anything else but the latest continuous release.
With this change, the release will still be called "continuous" but will have the visibility it needs (instead of some "old" release which is no longer supported).
=> Do not mark continuous as "prerelease"

scripts/docker/Dockerfile, scripts/docker/create-build-container.sh
Docker supports architecture-specific tagging now. No need to distinguish between them using architecture prefixes.
This PR is a preparation for automated updates of the Alpine release pinning via Dependabot or Renovate.
=> Remove superfluous architecture prefix

BUILD.md, README.md
This commit eliminates redundancies between README.md and BUILD.md. Not having to maintain redundant documentation is a big improvement as there is no chance they will be out of sync. Plus, the docs in BUILD.md are a bit more sophisticated while still allowing @probonopd to copy-and-paste commands for his workflow.
Additionally, the environment variable used in the chroot scripts has been fixed.
The commit further adds a short introduction explaining the differences between the build scripts and recommending Docker for regular users.
=> Improve build docs

.github/dependabot.yml
This should create automated PRs to update the pinned release in our Dockerfile, allowing us to make sure everything works before merging updates and roll them back easily if needed, as well as keep our GitHub actions pipelines up to date.
Closes #79
=> Use Dependabot to update Dockerfile and actions pipelines

.gitignore, scripts/chroot/build.sh, scripts/common/install-dependencies.sh, scripts/docker/Dockerfile, src/runtime/Makefile
It is not proven that it was the fact the binary was linked as PIE that caused https://github.com/AppImage/type2-runtime/issues/96 in edge cases. Therefore, re-adding it. @probonopd wants to test this more thoroughly now, but in theory, this can be merged.
=> Re-add PIE build flags

scripts/chroot/build.sh, scripts/chroot/chroot_build.sh
Hello all,
I am not namely a developer (more a sysadmin) but very interested to understand how AppImage works in details.
As I am trying to rebuild on my own this 'runtime', that Alpine base can be upgraded to take benefit of improvement (perf, security, ...).
For the moment, I am only able to test this build with the proposed Vagrantfile virtualbox VM (release 7.0.22) with chroot method and seems to complete with success (eventhought I don't know yet how to actually test it in an AppImage :()
Tia for kind attention, take care,
Rudy.
=> Suggest to bump alpine release to latest known today: 3.21.0.

scripts/docker/create-build-container.sh
Closes https://github.com/AppImage/type2-runtime/issues/112
=> Build with docker_platform=linux/arm/v6 to support RPi 1
